datacamp/rdocumentation-app

config/http.js
views/package_version/show.ejs

fixed relative url issue,
img url's are now redirected to 'base+/blob'
normal url's are redirected to the base

Fixed url issue

---

assets/js/dependencies/async_loader.js
views/layout.ejs
views/package_version/show.ejs

redirect tabclicks in Rstudio and solve https faults

finally solved tabs problem

---

api/controllers/PackageController.js
api/controllers/PackageVersionController.js
api/controllers/RstudioController.js
api/models/Alias.js
api/responses/rstudio_redirect.js
api/services/RStudioService.js
assets/js/dependencies/async_loader.js
assets/js/pages/package.js
assets/js/search.js
views/layout.ejs
views/package_version/show.ejs
views/shared/_footer.ejs

solved multiple problems in Rstudio with javascript
- loading of scripts is async in this browser -> wait for scripts
- unbind does not work in this browser ->bind functions only once
- document.ready gets executed each time on .html -> added boolean for executing once
- added timeout of one second to the full search so quicksearch does not appear over the full search page (due to slow javascript execution)

Tabs issue

---

assets/js/helpers/boot.js
assets/js/helpers/downloadStats.js

issue112 solved

---

assets/js/helpers/boot.js
assets/js/helpers/list-table-filtering.js
views/layout.ejs

fixed the continuous loading issue.

issue 122: fixed dcl issue

---

assets/js/dependencies/async_loader.js
assets/js/dependencies/rstudio_navigator.js
views/package_version/show.ejs
views/rStudio/make_default.ejs
views/topic/show.ejs

checking for package version invisible + hide run examples when need to install the package

made versionCheck invisible

---

assets/js/pages/trending.js

page loads once now, (deleted ajax request for undefined)

solved #129

---

assets/js/search.js
views/rStudio/list_options.ejs
views/rStudio/make_default.ejs
views/rStudio/topic_not_found.ejs
views/search/function_results.ejs

changed topics to functions in front end

issue118: 

---

api/controllers/CollaboratorController.js
api/controllers/PackageVersionController.js
api/models/DownloadStatistic.js
assets/js/helpers/downloadStats.js
assets/js/pages/collaborator.js
assets/styles/pages/_collaborator.scss
config/routes.js
views/collaborator/show.ejs
views/layout.ejs

Issue57: author page redesign

---

api/controllers/AuthController.js
assets/js/dependencies/async_loader.js
config/routes.js

rstudio_login fires on first page retrieval and after the normal login function

added an rstudio_login for #141

---

api/controllers/UserController.js
views/403.ejs
views/404.ejs
views/500.ejs
views/layout.ejs
views/shared/_example.ejs
views/user/show.ejs

solved issue161 and removed double footer and navbar of error pages

issue161 redid user page

---

api/controllers/AuthController.js
api/controllers/CollaboratorController.js
api/controllers/ReviewController.js
api/controllers/TaskViewController.js
api/controllers/TopicController.js
api/controllers/UserController.js
assets/js/dependencies/async_loader.js
assets/js/dependencies/rstudio_navigator.js
assets/js/helpers/boot.js
assets/js/pages/package.js
assets/js/pages/topic.js
views/layout.ejs
views/shared/_example.ejs

Boot refactoring

---

assets/js/dependencies/async_loader.js
assets/js/pages/topic.js

examples on user page running again

---

assets/js/dependencies/async_loader.js

versionNumber replace hyphens

---

views/layout.ejs

because of the SSL errors in Rstudio on windows

changed all https to http

---

api/services/ElasticSearchService.js

actually https://github.com/datacamp/rdocumentation-app/issues/224, but forgot to start new branch
(rebased on dev though)

added highlights and aliases filtering

---

api/controllers/HomeController.js
assets/styles/pages/_home.scss
views/homepage.ejs
views/shared/_navigation.ejs

the functions are changed in issue242 as mentioned in the comments the sort argument must be added when merged with that branch

Home table

---

assets/js/pages/examples.js
views/shared/_post_example.ejs
views/topic/show.ejs

Examples validation

---

assets/js/dependencies/async_loader.js
assets/js/dependencies/rstudio_requests.js
assets/js/helpers/utils.js

Use session id in RStudio instead of clear text credentials

Use session_id instead of username + password

---

assets/js/dependencies/async_loader.js
assets/js/dependencies/rstudio_requests.js

Fix the rpc for RStudio 1.0
Tested on RStudio 1.0, RStudio 0.99.
To be tested on RStudio Server when merged on staging

Fix/rstudio 1.0

---

views/layout.ejs

I set up the snippet, next step is to track actions. 
What do we want to track ?

Set up Segment

---

api/controllers/PackageController.js
api/controllers/TopicController.js
api/models/PackageVersion.js
api/models/Topic.js
api/services/PackageService.js
package.json
test/test-version-ordering.js
views/package_version/show.ejs

This should fix the version ordering issue

fix versions ordering

---

assets/js/helpers/boot.js
assets/js/helpers/utils.js
assets/styles/styleguide/partials/_footer.scss
views/layout.ejs
views/shared/_dc_footer.ejs

@filipsch (cc @martijnsublime @dwaynemartin )
the footer can be seen on https://dev.rdocumentation.org/packages/dplyr/versions/0.5.0
Is the styling in line with what you had in mind ?
@martijnsublime @dwaynemartin for now the link point to https://www.datacamp.com
do I have to put any tracking code in the query parameters ?

put the footer ad

---

assets/styles/pages/_search.scss
views/search/result.ejs

link to rdoc tech blog post

---

views/package_version/_details.ejs

I merge directly, but did the PR for transparency

fix the dependency link

---

api/models/Topic.js

also search in aliases

---

api/models/Topic.js

should fix https://github.com/datacamp/RDocumentation/issues/72

join with double line break when indexing topics

---

api/models/Topic.js

fix inefficient alias query

---

views/package_version/_details.ejs
views/package_version/_header.ejs
views/package_version/show.ejs

remove trailing slash in path

---

api/controllers/SearchController.js
assets/js/pages/search.js
assets/styles/pages/_search.scss
views/search/result.ejs
views/shared/_navbar.ejs

search in older versions

---

assets/styles/pages/_search.scss

Fixes the disabled scrollbar shown at search pages in Chrome

fix search scrollbar

---

CONTRIBUTING.md

Fix a minor typo in the lamba-worker URL.

fix minor typo

---

assets/js/libs/dc-modal.js
views/layout.ejs
views/shared/_dc_modal.ejs
views/shared/_snowplow.ejs

This PR will display a modal to 50% of visitors about the Tidyverse courses on DataCamp. It also installs Snowplow tracking.
Note: this PR also has a copy of #408 in it, so I'm going to close #408.

Add DataCamp Tidyverse Modal Experiment

---

assets/js/libs/experiment.js

This PR addresses the code review from before launching the Tidyverse modal experiment.

Fix #411: Improvements to the Experiment class

---

views/shared/_snowplow.ejs

Same as https://github.com/datacamp/enterprise-app/pull/763

Update Snowplow tracking

---

views/layout.ejs

https://datacamp.atlassian.net/browse/COMM-853

Make RDocs staging noindexed!

---

assets/styles/pages/_shared.scss
assets/styles/styleguide/partials/_navbar.scss
views/layout.ejs

This adds a promo banner script and changes the internal nav to be static.

feat(promo): add banner

---

views/shared/_dc_footer.ejs

Flying blind, will test on staging ![image](https://user-images.githubusercontent.com/283611/74165579-51384600-4bf3-11ea-92c1-5a7a62247e5a.png)
Pinged everyone just because `@growth` isn't available

feat(footer): change the cta to skill assessment

---

views/shared/_dc_footer.ejs

Small tweaks to the utm param values.

chore(footer): Update utm params

---

assets/js/dependencies/async_loader.js
views/layout.ejs

Link to ticket: https://datacamp.atlassian.net/browse/LO-309
- Use Mathjax v3, using https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html
- Typeset after dynamic render

[LO-309] fix: typeset after async load

---

README.md
api/models/Topic.js

Fixes [CT-3601](https://datacamp.atlassian.net/browse/CT-3601)
- Remove the logic around extracting arguments and putting them in their own table: they will be treated as a regular section instead
- Extract the contents from the description field since the db expects a string

[CT-3601] Update API to not handle some sections as custom

---

README.md
api/models/Topic.js

Reverts datacamp/RDocumentation-app#482

Revert "[CT-3601] Update API to not handle some sections as custom"

---

.circleci/config.yml

Context on slack: https://datacamp.slack.com/archives/C3Y59RP18/p1655477326606099?thread_ts=1654886056.053429&cid=C3Y59RP18

chore: update circleci deploy config

---

api/controllers/WorkerController.js
api/models/Topic.js
config/routes.js

Testing to see if a console.log will show up on Datadog.

chore: add console.log to test datadog logs

---

api/controllers/WorkerController.js

Added console.log to check deploy on aws ec2 in preparation for meeting

chore: check api deploy

---

api/controllers/TopicController.js

Jira: https://datacamp.atlassian.net/browse/COMM-5306
Revert changes to TopicController from PR #525

[COMM-5306] Revert changes to TopicController to fix RDocs

---

api/controllers/SearchController.js

Jira: https://datacamp.atlassian.net/browse/COMM-5586
Fix the error where some search queries return 500
[DataDog error](https://app.datadoghq.com/logs?query=service%3Ardoc-app%20status%3Aerror%20&cols=host%2Cservice&event=AgAAAYwndpACYo6MCgAAAAAAAAAYAAAAAEFZd25kcUE0QUFDaEdtcktFVlJneEFBQgAAACQAAAAAMDE4YzI3N2MtYjY2Yi00ODVhLWI5ODEtNzM2ZDhlOWRkMjRm&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1701469130000&to_ts=1701469140000&live=false) for [this query](https://api.rdocumentation.org/search_functions?q=all&page=1&latest=1)

[COMM-5586] Add safe guard if maintainer is undefined
